version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/prod-blog-backend/
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
      timeout: 60
      runas: ec2-user