version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/prod-blog-backend
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: root