version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
<<<<<<< HEAD
<<<<<<< HEAD
        TaskDefinition: "arn:aws:ecs:ap-south-1:122612862532:task-definition/parkging-blog-prod-family:1"
        LoadBalancerInfo:
          ContainerName: "parkging-blog-prod-container"
=======
<<<<<<<< HEAD:aws/dev/dev-appspec.yml
        TaskDefinition: "arn:aws:ecs:ap-south-1:122612862532:task-definition/parkging-blog-dev-family:1"
========
        TaskDefinition: "arn:aws:ecs:ap-south-1:122612862532:task-definition/blog-backend-family:3"
>>>>>>>> dc066e8 (add dev settings):aws/prod/prod-appspec.yml
        LoadBalancerInfo:
          ContainerName: "parkging-blog-dev-container"
>>>>>>> dc066e8 (add dev settings)
=======
        TaskDefinition: "arn:aws:ecs:ap-south-1:122612862532:task-definition/parkging-blog-prod-family:1"
        LoadBalancerInfo:
          ContainerName: "parkging-blog-prod-container"
>>>>>>> 25ee24b (Feature/add prod settings (#107))
          ContainerPort: 8080