version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
<<<<<<<< HEAD:aws/dev/dev-appspec.yml
        TaskDefinition: "arn:aws:ecs:ap-south-1:122612862532:task-definition/parkging-blog-dev-family:1"
========
        TaskDefinition: "arn:aws:ecs:ap-south-1:122612862532:task-definition/blog-backend-family:3"
>>>>>>>> dc066e8 (add dev settings):aws/prod/prod-appspec.yml
        LoadBalancerInfo:
          ContainerName: "parkging-blog-dev-container"
          ContainerPort: 8080