version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:122612862532:task-definition/parkging-blog-dev-family:1"
        LoadBalancerInfo:
          ContainerName: "parkging-blog-dev-container"
          ContainerPort: 8080