name: Build and Deploy Master Branch

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ap-south-1  # 뭄바이
  ECR_REPOSITORY: blog-backend-ecr
  ECS_CLUSTER: prod-blog-backend-cluster
  ECS_SERVICE: prod-blog-backend-service
  CONTAINER_NAME: blog-backend-container
  CODEDEPLOY_APPSPEC: ./aws/prod/prod-appspec.yml
  CODEDEPLOY_APPLICATION: AppECS-prod-blog-backend-cluster-prod-blog-backend-service
  CODEDEPLOY_DEPLOYMENT_GROUP: DgpECS-prod-blog-backend-cluster-prod-blog-backend-service
  ECS_TASK_DEFINITION: ./aws/prod/prod-task-definition.json
#  ECS_TASK_DEFINITION: ${{ github.ref == 'refs/heads/master' && 'prod-task-definition.json' || 'dev-task-definition.json' }}

jobs:
  deploy:

    name: Deploy Prod ECS
    runs-on: ubuntu-latest

    steps:

      # Source Code Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Setting AWS Access Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Java Setting
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      # Github Repository Secrets를 통해 환경 변수 파일을 생성.
      - name: Generate Environment Variables File for Production
        env:
          APPLICATION_PROD_PROPERTIES: ${{ secrets.APPLICATION_PROD_PROPERTIES }}
          DATABASE_PROD_PROPERTIES: ${{ secrets.DATABASE_PROD_PROPERTIES }}
          APPLICATION_SECURITY_PROD_PROPERTIES: ${{ secrets.APPLICATION_SECURITY_PROD_PROPERTIES }}
        run: |
          echo -e "$APPLICATION_PROD_PROPERTIES" >> ./src/main/resources/application-prod.properties
          echo -e "$DATABASE_PROD_PROPERTIES" >> ./src/main/resources/database-prod.properties
          echo -e "$APPLICATION_SECURITY_PROD_PROPERTIES" >> ./src/main/resources/application-security-prod.properties

      # Gradle wrapper 파일 실행 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Gradle Build
      - name: Build with Gradle
        run: |
          SPRING_PROFILES_ACTIVE=prod ./gradlew clean build --info --stacktrace

      # ECR Login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # ECR Build and Push Docker Image
      - name: Build and Push
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./aws/prod/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      # Setting Image Id to env
      - name: Image digest
        id: image-digest
        run: |
          echo "image=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}" >> $GITHUB_OUTPUT

      # Fill Image Id and env on task definition
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.image-digest.outputs.image }}
          environment-variables: |
            BLOG_OP_ENV=prod
            ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY_VALUE }}

      # Task Definition Deploy
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
          codedeploy-appspec: ${{ env.CODEDEPLOY_APPSPEC }}
          codedeploy-application: ${{ env.CODEDEPLOY_APPLICATION }}
          codedeploy-deployment-group: ${{ env.CODEDEPLOY_DEPLOYMENT_GROUP }}